=== onikolaiev/netServer/Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Definitions">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="RealmPacket" type="packetDefinition"/>
        <xs:element name="AuthPacket" type="packetDefinition"/>
      </xs:choice>
      <xs:attribute name="Version" type="xs:positiveInteger"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="packetDefinition">
        <xs:sequence>
          <xs:element name="OpCodes" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="OpCode" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
        </xs:element>
        <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="OpCode" type="xs:string" use="optional"/>
        <xs:attribute name="Sender" use="optional">
          <xs:simpleType id="PacketSender">
            <xs:restriction base="xs:string">
              <xs:enumeration value="Client"/>
              <xs:enumeration value="Server"/>
              <xs:enumeration value="Any"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
</xs:complexType>

      <xs:group name="optionallyNamedSegmentList">
        <xs:sequence>
          <xs:element name="Name" type="xs:string" minOccurs="0"/>
          <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:group>

      <xs:group name="segmentList">
        <xs:choice>
          <xs:element name="Simple">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Type" type="simpleType"/>
                <xs:element name="SegmentType" type="xs:string" minOccurs="0" maxOccurs="1"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="Complex">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string" minOccurs="0"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="List">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Type" type="simpleType" minOccurs="0"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
              <xs:attribute name="LengthSegment" type="xs:string" use="optional"/>
              <xs:attribute name="LengthExpr" type="xs:string" use="optional"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="StaticList">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
              <xs:attribute name="Length" type="xs:positiveInteger"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="Switch">
            <xs:complexType>
              <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="Case">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                    <xs:attribute name="Equals" use="optional"/>
                    <xs:attribute name="NotEqual" use="optional"/>
                    <xs:attribute name="GreaterThan" use="optional"/>
                    <xs:attribute name="GreaterOrEqual" use="optional"/>
                    <xs:attribute name="LessThan" use="optional"/>
                    <xs:attribute name="LessOrEqual" use="optional"/>
                    <xs:attribute name="And" use="optional"/>
                    <xs:attribute name="AndAny" use="optional"/>
                    <xs:attribute name="AndNot" use="optional"/>
                    <xs:attribute name="Either" use="optional"/>
                    <xs:attribute name="Neither" use="optional"/>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
              <xs:attribute name="CompareWith" type="xs:string"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="FinalList">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:choice>
      </xs:group>

      <xs:group name="namedSegmentList">
        <xs:sequence>
          <xs:element name="Name" type="xs:string"/>
          <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:group>

      <xs:simpleType name="simpleType">
        <xs:restriction base="xs:string">
          <xs:enumeration value="Byte"/>
          <xs:enumeration value="UShort"/>
          <xs:enumeration value="Short"/>
          <xs:enumeration value="UInt"/>
          <xs:enumeration value="Int"/>
          <xs:enumeration value="ULong"/>
          <xs:enumeration value="Long"/>
          <xs:enumeration value="Float"/>
          <xs:enumeration value="Guid"/>
          <xs:enumeration value="Vector3"/>
          <xs:enumeration value="PackedVector3"/>
          <xs:enumeration value="Vector4"/>
          <xs:enumeration value="PackedGuid"/>
          <xs:enumeration value="CString"/>
          <xs:enumeration value="PascalStringByte"/>
          <xs:enumeration value="PascalStringUShort"/>
          <xs:enumeration value="PascalStringUInt"/>
          <xs:enumeration value="Guid"/>
		  <xs:enumeration value="UnixTime"/>
		  <xs:enumeration value="PackedDate"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:schema>

=== onikolaiev/netServer/Run/Content/Packets/Loot.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">
  <RealmPacket OpCode="SMSG_LOOT_START_ROLL">
    <Simple>
      <Name>Looted</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>ItemIndex</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>ItemTemplate</Name>
      <Type>UInt</Type>
      <SegmentType>Items.ItemId</SegmentType>
    </Simple>
    <Simple>
      <Name>Unk1</Name>
      <Type>Int</Type>
    </Simple>
    <Simple>
      <Name>Unk2</Name>
      <Type>Int</Type>
    </Simple>
    <Simple>
      <Name>TimeoutMillis</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_LOOT_ROLL">
    <Simple>
      <Name>Looted</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>ItemIndex</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Looter</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>ItemTemplate</Name>
      <Type>UInt</Type>
      <SegmentType>Items.ItemId</SegmentType>
    </Simple>
    <Simple>
      <Name>Unk1</Name>
      <Type>Int</Type>
    </Simple>
    <Simple>
      <Name>Unk2</Name>
      <Type>Int</Type>
    </Simple>
    <Simple>
      <Name>Roll</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>RollType</Name>
      <Type>Byte</Type>
      <SegmentType>Looting.LootRollType</SegmentType>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_LOOT_ROLL">
    <Simple>
      <Name>Looted</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>ItemIndex</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>RollType</Name>
      <Type>Byte</Type>
      <SegmentType>Looting.LootRollType</SegmentType>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_LOOT_RESPONSE">
    <Simple>
      <Name>Looted</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Looting.LootResponseType</Name>
      <Type>Byte</Type>
      <SegmentType>Looting.LootResponseType</SegmentType>
    </Simple>
    <Simple>
      <Name>Money</Name>
      <Type>UInt</Type>
    </Simple>
    <List>
      <Name>Items</Name>
      <Type>Byte</Type>

      <Simple>
        <Name>Index</Name>
        <Type>Byte</Type>
      </Simple>
      <Simple>
        <Name>ItemId</Name>
        <Type>UInt</Type>
        <SegmentType>Items.ItemId</SegmentType>
      </Simple>
      <Simple>
        <Name>Amount</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>DisplayId</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>RandomSuffixFactor</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>RandomPropertiesId</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>Decision</Name>
        <Type>Byte</Type>
        <SegmentType>Looting.LootDecision</SegmentType>
      </Simple>
    </List>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_OPT_OUT_OF_LOOT">
    <Simple>
      <Name>AutoOptOut (boolean)</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>
</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/Mail.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">
  <RealmPacket OpCode="CMSG_SEND_MAIL">
    <Simple>
      <Name>Mailbox</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Receiver</Name>
      <Type>CString</Type>
    </Simple>
    <Simple>
      <Name>Subject</Name>
      <Type>CString</Type>
    </Simple>
    <Simple>
      <Name>Body</Name>
      <Type>CString</Type>
    </Simple>
    <Simple>
      <Name>Stationary</Name>
      <Type>UInt</Type>
      <SegmentType>MailStationary</SegmentType>
    </Simple>
    <Simple>
      <Name>Unknown1</Name>
      <Type>UInt</Type>
    </Simple>
    <List>
      <Name>Items</Name>
      <Type>Byte</Type>
      <Simple>
        <Name>Slot</Name>
        <Type>Byte</Type>
      </Simple>
      <Simple>
        <Name>ItemId</Name>
        <Type>Guid</Type>
      </Simple>
    </List>
    <Simple>
      <Name>Money</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>CoD</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Unknown2</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Unknown3</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_SEND_MAIL_RESULT">
    <Simple>
      <Name>MailId</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Result</Name>
      <Type>UInt</Type>
      <SegmentType>MailResult</SegmentType>
    </Simple>
    <Simple>
      <Name>Error</Name>
      <Type>UInt</Type>
      <SegmentType>MailError</SegmentType>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_GET_MAIL_LIST">
    <Simple>
      <Name>Mailbox EntityId</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_MAIL_TAKE_MONEY">
    <Simple>
      <Name>Mailbox EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Mail MessageId</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_MAIL_TAKE_ITEM">
    <Simple>
      <Name>Mailbox EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Mail MessageId</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Item EntityLowId</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_MAIL_MARK_AS_READ">
    <Simple>
      <Name>Mailbox EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Mail MessageId</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_MAIL_RETURN_TO_SENDER">
    <Simple>
      <Name>Mailbox EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Mail MessageId</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_MAIL_DELETE">
    <Simple>
      <Name>Mailbox EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Mail MessageId</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Unknown</Name>
      <Type>Int</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_MAIL_CREATE_TEXT_ITEM">
    <Simple>
      <Name>Mailbox EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Mail MessageId</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_RECEIVED_MAIL"/>

  <RealmPacket OpCode="SMSG_MAIL_LIST_RESULT">
    <Simple>
      <Name>RealCount</Name>
      <Type>UInt</Type>
    </Simple>
    <List>
      <Name>Messages</Name>
      <Type>Byte</Type>
      <Simple>
        <Name>Version-Dependent Constant (0x0040, 0x024C)</Name>
        <Type>UShort</Type>
      </Simple>
      <Simple>
        <Name>MessageId</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>MailType</Name>
        <Type>Byte</Type>
        <SegmentType>MailType</SegmentType>
      </Simple>
      <Switch CompareWith="MailType">
        <Case Equals="Normal">
          <Simple>
            <Name>Sender EntityId</Name>
            <Type>Guid</Type>
          </Simple>
        </Case>
        <Case Equals="Creature">
          <Simple>
            <Name>Sender EntityLowId</Name>
            <Type>UInt</Type>
          </Simple>
        </Case>
        <Case Equals="GameObject">
          <Simple>
            <Name>Sender EntityLowId</Name>
            <Type>UInt</Type>
          </Simple>
        </Case>
        <Case Equals="Auction">
          <Simple>
            <Name>Auction Id</Name>
            <Type>UInt</Type>
          </Simple>
        </Case>
        <Case Equals="Item">
          <Simple>
            <Name>Sender EntityLowId</Name>
            <Type>UInt</Type>
          </Simple>
        </Case>
      </Switch>
      <Simple>
        <Name>CoD</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>TextItem EntityLowId</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>Unknown 0</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>Stationary</Name>
        <Type>UInt</Type>
        <SegmentType>MailStationary</SegmentType>
      </Simple>
      <Simple>
        <Name>Money</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>ButtonFlags</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>ExpiryInDays</Name>
        <Type>Float</Type>
      </Simple>
      <Simple>
        <Name>Unk02</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>Subject</Name>
        <Type>CString</Type>
      </Simple>
      <List>
        <Name>Items</Name>
        <Type>Byte</Type>
        <Simple>
          <Name>Slot</Name>
          <Type>Byte</Type>
        </Simple>
        <Simple>
          <Name>ItemEntityLowId</Name>
          <Type>UInt</Type>
        </Simple>
        <Simple>
          <Name>ItemTemplate</Name>
          <Type>UInt</Type>
        </Simple>
        <StaticList Length="7">
          <Name>Enchants</Name>
          <Simple>
            <Name>Charges</Name>
            <Type>UInt</Type>
          </Simple>
          <Simple>
            <Name>Duration</Name>
            <Type>UInt</Type>
          </Simple>
          <Simple>
            <Name>Id</Name>
            <Type>UInt</Type>
          </Simple>
        </StaticList>
        <Simple>
          <Name>Random Property Id</Name>
          <Type>Int</Type>
        </Simple>
        <Simple>
          <Name>Random Suffix Id</Name>
          <Type>Int</Type>
        </Simple>
        <Simple>
          <Name>Amount</Name>
          <Type>Int</Type>
        </Simple>
        <Simple>
          <Name>Charges</Name>
          <Type>UInt</Type>
        </Simple>
        <Simple>
          <Name>MaxDurability</Name>
          <Type>UInt</Type>
        </Simple>
        <Simple>
          <Name>Durability</Name>
          <Type>Int</Type>
        </Simple>
        <Simple>
          <Name>UnkWotlk1</Name>
          <Type>Byte</Type>
        </Simple>
      </List>
    </List>
  </RealmPacket>

  <RealmPacket Sender="Client" OpCode="MSG_QUERY_NEXT_MAIL_TIME"/>

  <RealmPacket Sender="Server" OpCode="MSG_QUERY_NEXT_MAIL_TIME">
    <Simple>
      <Name>UnkFloat</Name>
      <Type>Float</Type>
    </Simple>
    <List>
      <Name>MessagesCount</Name>
      <Type>UInt</Type>
      <Simple>
        <Name>SenderEntityId</Name>
        <Type>Guid</Type>
      </Simple>
      <Simple>
        <Name>UnknownUInt_1 (2 for auction, 0 else)</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>UnknownUInt_2 (2 for auction, 0 else)</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>MessageStationary</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>UnkownFloat</Name>
        <Type>Float</Type>
      </Simple>
    </List>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_ITEM_TEXT_QUERY">
    <Simple>
      <Name>ItemTextId</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>MailOrItemEntityLowId</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Unknown</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_ITEM_TEXT_QUERY_RESPONSE">
    <Simple>
      <Name>ItemTextId</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Text</Name>
      <Type>CString</Type>
    </Simple>
  </RealmPacket>
</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/BattleGrounds.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">

  <RealmPacket OpCode="CMSG_BATTLEMASTER_HELLO">
    <Simple>
      <Name>BattleMaster</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_BATTLEFIELD_LIST">
    <Simple>
      <Name>Battleground</Name>
      <Type>UInt</Type>
      <SegmentType>BattlegroundId</SegmentType>
    </Simple>
    <Simple>
      <Name>From UI</Name>
      <Type>Byte</Type>
    </Simple>
  </RealmPacket>
  
  <RealmPacket OpCode="SMSG_BATTLEFIELD_LIST">
    <Simple>
      <Name>BattleMaster</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>FromGUI</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>Battleground</Name>
      <Type>UInt</Type>
      <SegmentType>BattlegroundId</SegmentType>
    </Simple>
    <Simple>
      <Name>Level Bracket</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>Unk333</Name>
      <Type>Byte</Type>
    </Simple>
    <List>
      <Name>Battlegrounds</Name>
      <Type>UInt</Type>
      <Simple>
        <Name>Battleground</Name>
        <Type>UInt</Type>
      </Simple>
    </List>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_BATTLEMASTER_JOIN">
    <Simple>
      <Name>BattleMaster</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>BattlegroundId</Name>
      <Type>UInt</Type>
      <SegmentType>WCell.Constants.BattlegroundId</SegmentType>
    </Simple>
    <Simple>
      <Name>InstanceId</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>JoinAsGroup</Name>
      <Type>Byte</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_BATTLEFIELD_STATUS">
    <Simple>
      <Name>QueueSlot</Name>
      <Type>Int</Type>
    </Simple>

    <Simple>
      <Name>BGID ArenaType</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>BGID Level Bracket</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>BGID BattlegroundId</Name>
      <Type>UInt</Type>
      <SegmentType>WCell.Constants.BattlegroundId</SegmentType>
    </Simple>
    <Simple>
      <Name>BGID Field_6</Name>
      <Type>UShort</Type>
    </Simple>

    <Switch CompareWith="BGID BattlegroundId">
      <Case NotEqual="0">
        <Simple>
          <Name>Unk2</Name>
          <Type>Int</Type>
        </Simple>

        <Simple>
          <Name>Is Rated Match</Name>
          <Type>Byte</Type>
        </Simple>

        <Simple>
          <Name>Status</Name>
          <Type>UInt</Type>
          <SegmentType>BattlegroundStatus</SegmentType>
        </Simple>

        <Switch CompareWith="Status">
          <Case Equals="Enqueued">
            <Simple>
              <Name>WaitTime</Name>
              <Type>UInt</Type>
            </Simple>
            <Simple>
              <Name>TimeEnqueued</Name>
              <Type>UInt</Type>
            </Simple>
          </Case>
          <Case Equals="Preparing">
            <Simple>
              <Name>MapId</Name>
              <Type>UInt</Type>
              <SegmentType>World.MapId</SegmentType>
            </Simple>
            <Simple>
              <Name>QueueTimeout</Name>
              <Type>UInt</Type>
            </Simple>
          </Case>
          <Case Equals="Active">
            <Simple>
              <Name>MapId</Name>
              <Type>UInt</Type>
              <SegmentType>World.MapId</SegmentType>
            </Simple>
            <Simple>
              <Name>Time until Expiration</Name>
              <Type>UInt</Type>
            </Simple>
            <Simple>
              <Name>Time Active</Name>
              <Type>UInt</Type>
            </Simple>
            <Simple>
              <Name>Arena Faction</Name>
              <Type>Byte</Type>
            </Simple>
          </Case>
        </Switch>
      </Case>
    </Switch>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_BATTLEFIELD_PORT">
    <Simple>
      <Name>BGID ArenaType</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>BGID Level Bracket</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>BGID BattlegroundId</Name>
      <Type>UInt</Type>
      <SegmentType>WCell.Constants.BattlegroundId</SegmentType>
    </Simple>
    <Simple>
      <Name>BGID Field_6</Name>
      <Type>UShort</Type>
    </Simple>
    <Simple>
      <Name>Port Accepted</Name>
      <Type>Byte</Type>
    </Simple>
  </RealmPacket>


  <RealmPacket OpCode="MSG_PVP_LOG_DATA" Sender="Server">
    <Simple>
      <Name>Is Arena</Name>
      <Type>Byte</Type>
    </Simple>
    <Switch CompareWith="Is Arena">
      <Case Equals="1">
        <StaticList Length="2">
          <Name>Arena Team Info</Name>

          <Simple>
            <Name>Rating Change</Name>
            <Type>Int</Type>
          </Simple>
          <Simple>
            <Name>Arena Unk</Name>
            <Type>Int</Type>
          </Simple>
        </StaticList>

        <StaticList Length="2">
          <Name>Arena Team Names</Name>

          <Simple>
            <Name>Team Name</Name>
            <Type>CString</Type>
          </Simple>          
        </StaticList>
      </Case>
    </Switch>

    <Simple>
      <Name>BG Completed</Name>
      <Type>Byte</Type>
    </Simple>

    <Switch CompareWith="BG Completed">
      <Case Equals="1">
        <Simple>
          <Name>Winning Team</Name>
          <Type>Byte</Type>
        </Simple>
      </Case>
    </Switch>

    <List>
      <Name>Score Count</Name>
      <Type>Int</Type>

      <Simple>
        <Name>Player</Name>
        <Type>Guid</Type>
      </Simple>
      <Simple>
        <Name>Killing Blows</Name>
        <Type>Int</Type>
      </Simple>

      <Switch CompareWith="Is Arena">
        <Case Equals="1">
          <Simple>
            <Name>Is On Winning Team</Name>
            <Type>Byte</Type>
          </Simple>
        </Case>
        <Case Equals="0">
          <Simple>
            <Name>Honorable Kills</Name>
            <Type>Int</Type>
          </Simple>
          <Simple>
            <Name>Deaths</Name>
            <Type>Int</Type>
          </Simple>
          <Simple>
            <Name>Bonus Honor</Name>
            <Type>Int</Type>
          </Simple>
        </Case>
      </Switch>

      <Simple>
        <Name>Damage Done</Name>
        <Type>Int</Type>
      </Simple>
      <Simple>
        <Name>Healing Done</Name>
        <Type>Int</Type>
      </Simple>

      <List>
        <Name>BG Specific Data</Name>
        <Type>Int</Type>

        <Simple>
          <Name>Data</Name>
          <Type>Int</Type>
        </Simple>
      </List>
    </List>
  </RealmPacket>

  <RealmPacket OpCode="MSG_PVP_LOG_DATA" Sender ="Client">
    <!-- This is just a request, therefore empty-->
  </RealmPacket>

  <RealmPacket OpCode="MSG_BATTLEGROUND_PLAYER_POSITIONS" Sender="Server">
    <Simple>
      <Name>Player Count</Name>
      <Type>Int</Type>
    </Simple>
    <List LengthSegment="Player Count">
      <Name>Team Positions</Name>

      <Simple>
        <Name>Player</Name>
        <Type>Guid</Type>
      </Simple>
      <Simple>
        <Name>Position.X</Name>
        <Type>Float</Type>
      </Simple>
      <Simple>
        <Name>Position.Y</Name>
        <Type>Float</Type>
      </Simple>
    </List>

    <Simple>
      <Name>Flag Carrier Count</Name>
      <Type>Int</Type>
    </Simple>

    <List LengthSegment="Flag Carrier Count">
      <Name>Flag Carriers</Name>
      
      <Simple>
        <Name>Flag Carrier</Name>
        <Type>Guid</Type>
      </Simple>
      <Simple>
        <Name>Position.X</Name>
        <Type>Float</Type>
      </Simple>
      <Simple>
        <Name>Position.Y</Name>
        <Type>Float</Type>
      </Simple>
    </List>
  </RealmPacket>

  <RealmPacket OpCode="MSG_BATTLEGROUND_PLAYER_POSITIONS" Sender="Client">
    <!-- This is just a request, therefore empty-->
  </RealmPacket>

  <RealmPacket OpCode="CMSG_LEAVE_BATTLEFIELD" Sender="Client">
    <Simple>
      <Name>BGID ArenaType</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>BGID Level Bracket</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>BGID BattlegroundId</Name>
      <Type>UInt</Type>
      <SegmentType>WCell.Constants.BattlegroundId</SegmentType>
    </Simple>
    <Simple>
      <Name>BGID Field_6</Name>
      <Type>UShort</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_BATTLEGROUND_PLAYER_JOINED" Sender="Server">
    <Simple>
      <Name>Player Id</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>
  
</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/World.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">

  <RealmPacket OpCode="SMSG_INIT_WORLD_STATES">
    <Simple>
      <Name>Region</Name>
      <Type>UInt</Type>
      <SegmentType>World.MapId</SegmentType>
    </Simple>
    <Simple>
      <Name>Zone</Name>
      <Type>UInt</Type>
      <SegmentType>World.ZoneId</SegmentType>
    </Simple>
    <Simple>
      <Name>Area</Name>
      <Type>UInt</Type>
    </Simple>
    <List>
      <Name>States</Name>
      <Type>UShort</Type>

      <Simple>
        <Name>Key</Name>
        <Type>UInt</Type>
        <SegmentType>World.WorldStateId</SegmentType>
      </Simple>
      <Simple>
        <Name>Value</Name>
        <Type>UInt</Type>
      </Simple>
    </List>
  </RealmPacket>
  
  <RealmPacket OpCode="SMSG_UPDATE_WORLD_STATE">
    <Simple>
      <Name>Key</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Value</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>
  
</Definitions>
