=== onikolaiev/netServer/Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Definitions">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="RealmPacket" type="packetDefinition"/>
        <xs:element name="AuthPacket" type="packetDefinition"/>
      </xs:choice>
      <xs:attribute name="Version" type="xs:positiveInteger"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="packetDefinition">
        <xs:sequence>
          <xs:element name="OpCodes" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="OpCode" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
        </xs:element>
        <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="OpCode" type="xs:string" use="optional"/>
        <xs:attribute name="Sender" use="optional">
          <xs:simpleType id="PacketSender">
            <xs:restriction base="xs:string">
              <xs:enumeration value="Client"/>
              <xs:enumeration value="Server"/>
              <xs:enumeration value="Any"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
</xs:complexType>

      <xs:group name="optionallyNamedSegmentList">
        <xs:sequence>
          <xs:element name="Name" type="xs:string" minOccurs="0"/>
          <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:group>

      <xs:group name="segmentList">
        <xs:choice>
          <xs:element name="Simple">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Type" type="simpleType"/>
                <xs:element name="SegmentType" type="xs:string" minOccurs="0" maxOccurs="1"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="Complex">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string" minOccurs="0"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="List">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Type" type="simpleType" minOccurs="0"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
              <xs:attribute name="LengthSegment" type="xs:string" use="optional"/>
              <xs:attribute name="LengthExpr" type="xs:string" use="optional"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="StaticList">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
              <xs:attribute name="Length" type="xs:positiveInteger"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="Switch">
            <xs:complexType>
              <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="Case">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                    <xs:attribute name="Equals" use="optional"/>
                    <xs:attribute name="NotEqual" use="optional"/>
                    <xs:attribute name="GreaterThan" use="optional"/>
                    <xs:attribute name="GreaterOrEqual" use="optional"/>
                    <xs:attribute name="LessThan" use="optional"/>
                    <xs:attribute name="LessOrEqual" use="optional"/>
                    <xs:attribute name="And" use="optional"/>
                    <xs:attribute name="AndAny" use="optional"/>
                    <xs:attribute name="AndNot" use="optional"/>
                    <xs:attribute name="Either" use="optional"/>
                    <xs:attribute name="Neither" use="optional"/>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
              <xs:attribute name="CompareWith" type="xs:string"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="FinalList">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:choice>
      </xs:group>

      <xs:group name="namedSegmentList">
        <xs:sequence>
          <xs:element name="Name" type="xs:string"/>
          <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:group>

      <xs:simpleType name="simpleType">
        <xs:restriction base="xs:string">
          <xs:enumeration value="Byte"/>
          <xs:enumeration value="UShort"/>
          <xs:enumeration value="Short"/>
          <xs:enumeration value="UInt"/>
          <xs:enumeration value="Int"/>
          <xs:enumeration value="ULong"/>
          <xs:enumeration value="Long"/>
          <xs:enumeration value="Float"/>
          <xs:enumeration value="Guid"/>
          <xs:enumeration value="Vector3"/>
          <xs:enumeration value="PackedVector3"/>
          <xs:enumeration value="Vector4"/>
          <xs:enumeration value="PackedGuid"/>
          <xs:enumeration value="CString"/>
          <xs:enumeration value="PascalStringByte"/>
          <xs:enumeration value="PascalStringUShort"/>
          <xs:enumeration value="PascalStringUInt"/>
          <xs:enumeration value="Guid"/>
		  <xs:enumeration value="UnixTime"/>
		  <xs:enumeration value="PackedDate"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:schema>

=== onikolaiev/netServer/Run/Content/Packets/Gossips.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">
  <RealmPacket OpCode="CMSG_GOSSIP_HELLO">
    <Simple>
      <Name>Target</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>
  
  <RealmPacket OpCode="CMSG_GOSSIP_SELECT_OPTION">
    <Simple>
      <Name>Target</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Option</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>
  
  <RealmPacket OpCode="SMSG_GOSSIP_MESSAGE">
    <Simple>
      <Name>Owner</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Unknown</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Body Text's Id</Name>
      <Type>UInt</Type>
    </Simple>
    <List>
      <Name>Gossip Items</Name>
      <Type>UInt</Type>
      <Simple>
        <Name>Id</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>Type</Name>
        <Type>Byte</Type>
        <SegmentType>GossipMenuIcon</SegmentType>
      </Simple>
      <Simple>
        <Name>Input</Name>
        <Type>Byte</Type>
      </Simple>
      <Simple>
        <Name>Required Money</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>Text</Name>
        <Type>CString</Type>
      </Simple>
      <Simple>
        <Name>Accept Text</Name>
        <Type>CString</Type>
      </Simple>
    </List>
    <List>
      <Name>Quest Items</Name>
      <Type>UInt</Type>
      <Simple>
        <Name>Id</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>Status</Name>
        <Type>UInt</Type>
        <!--<SegmentType>Quests.QuestStatus</SegmentType>-->
      </Simple>
      <Simple>
        <Name>Level</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>Text</Name>
        <Type>CString</Type>
      </Simple>
    </List>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_GOSSIP_COMPLETE"></RealmPacket>
</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/Combat.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">

  <RealmPacket OpCode="SMSG_ATTACKERSTATEUPDATE">
    <Simple>
      <Name>HitFlags</Name>
      <Type>UInt</Type>
      <SegmentType>HitFlags</SegmentType>
    </Simple>
    <Simple>
      <Name>Attacker</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <Simple>
      <Name>Target</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <Simple>
      <Name>TotalDamage</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <!--Overkill?-->
      <Name>Int_1</Name>
      <Type>Int</Type>
    </Simple>
    <Simple>
      <Name>DamageCount</Name>
      <Type>Byte</Type>
    </Simple>

    <List LengthSegment="DamageCount">
      <Name>Damages</Name>
      <Simple>
        <Name>DamageSchoolMask</Name>
        <Type>UInt</Type>
        <SegmentType>DamageSchoolMask</SegmentType>
      </Simple>
      <Simple>
        <Name>Float Damage</Name>
        <Type>Float</Type>
      </Simple>
      <Simple>
        <Name>Int Damage</Name>
        <Type>Int</Type>
      </Simple>
    </List>

    <Switch CompareWith="HitFlags">
      <Case And="AbsorbType1, AbsorbType2">
        <List LengthSegment="DamageCount">
          <Name>Absorb_1</Name>
          <Simple>
            <Name>Absorbed</Name>
            <Type>Int</Type>
          </Simple>
        </List>
      </Case>
      <!--Case And="Absorb_2">
        <List LengthSegment="DamageCount">
          <Name>Absorb_2</Name>
          <Simple>
            <Name>Absorbed</Name>
            <Type>Int</Type>
          </Simple>
        </List>
      </Case-->
    </Switch>
    <Switch CompareWith="HitFlags">
      <Case And="ResistType1, ResistType2">
        <List LengthSegment="DamageCount">
          <Name>Resist_1</Name>
          <Simple>
            <Name>Resisted</Name>
            <Type>Int</Type>
          </Simple>
        </List>
      </Case>
      <!--Case And="Resist_2">
        <List LengthSegment="DamageCount">
          <Name>Resist_2</Name>
          <Simple>
            <Name>Resisted</Name>
            <Type>Int</Type>
          </Simple>
        </List>
      </Case-->
    </Switch>

    <Simple>
      <Name>VictimState</Name>
      <Type>Byte</Type>
      <SegmentType>VictimState</SegmentType>
    </Simple>
    <Simple>
      <!--In case of Evade: 16777218; If no damage: 0;  Else: -1, 1000-->
      <Name>Int_2</Name>
      <Type>Int</Type>
    </Simple>
    <Simple>
      <Name>Int_3 - SpellId</Name>
      <Type>UInt</Type>
      <SegmentType>Spells.SpellId</SegmentType>
    </Simple>

    <Switch CompareWith="HitFlags">
      <Case And="Block">
        <Simple>
          <Name>Blocked</Name>
          <Type>Int</Type>
        </Simple>
      </Case>

      <!--Case And="<0x800000">
        <Simple>
          <Name>Flag_0x800000 Int</Name>
          <Type>Int</Type>
        </Simple>
      </Case>

      <Case And="1">
        <Simple>
          <Name>Flag_0x1 Int</Name>
          <Type>Int</Type>
        </Simple>

        <Simple>
          <Name>Flag_0x1 Float_1</Name>
          <Type>Float</Type>
        </Simple>
        <Simple>
          <Name>Flag_0x1 Float_2</Name>
          <Type>Float</Type>
        </Simple>
        <Simple>
          <Name>Flag_0x1 Float_3</Name>
          <Type>Float</Type>
        </Simple>
        <Simple>
          <Name>Flag_0x1 Float_4</Name>
          <Type>Float</Type>
        </Simple>
        <Simple>
          <Name>Flag_0x1 Float_5</Name>
          <Type>Float</Type>
        </Simple>
        <Simple>
          <Name>Flag_0x1 Float_6</Name>
          <Type>Float</Type>
        </Simple>
        <Simple>
          <Name>Flag_0x1 Float_7</Name>
          <Type>Float</Type>
        </Simple>
        <Simple>
          <Name>Flag_0x1 Float_8</Name>
          <Type>Float</Type>
        </Simple>

        <StaticList Length="5">
          <Name>Flag_0x1 Float List</Name>
          <Simple>
            <Name>Flag_0x1 FloatList 1</Name>
            <Type>Float</Type>
          </Simple>
          <Simple>
            <Name>Flag_0x1 FloatList 2</Name>
            <Type>Float</Type>
          </Simple>
        </StaticList>

        <Simple>
          <Name>Flag_0x1 Int_2</Name>
          <Type>Int</Type>
        </Simple>
      </Case>-->
    </Switch>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_HIGHEST_THREAT_UPDATE">
    <Simple>
      <Name>Packed Guid</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <Simple>
      <Name>New Primary Target</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <List>
      <Name>Threat List</Name>
      <Type>Int</Type>
      <Simple>
        <Name>Unit</Name>
        <Type>PackedGuid</Type>
      </Simple>
      <Simple>
        <Name>Threat Level</Name>
        <Type>Int</Type>
      </Simple>
    </List>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_THREAT_UPDATE">
    <Simple>
      <Name>Guid</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <List>
      <Name>Threat List</Name>
      <Type>Int</Type>
      <Simple>
        <Name>Unit</Name>
        <Type>PackedGuid</Type>
      </Simple>
      <Simple>
        <Name>Threat Level</Name>
        <Type>Int</Type>
      </Simple>
    </List>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_AI_REACTION">
    <Simple>
      <Name>Guid</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>AI Reaction</Name>
      <Type>UInt</Type>
      <!--Is there an enum for this?-->
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_ATTACKSWING">
    <Simple>
      <Name>Attacker</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_SETSHEATHED">
    <Simple>
      <Name>Sheath Type</Name>
      <Type>UInt</Type>
      <SegmentType>SheathType</SegmentType>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_ATTACKSTART">
    <Simple>
      <Name>Attacker</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Victim</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_ATTACKSTOP" />
  
  <RealmPacket OpCode="SMSG_ATTACKSTOP">
    <Simple>
      <Name>Attacker</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <Simple>
      <Name>Defender</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <Simple>
      <Name>Unknown Int</Name>
      <Type>Int</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_CANCEL_AUTO_REPEAT">
    <Simple>
      <Name>Character</Name>
      <Type>PackedGuid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_AI_REACTION">
    <Simple>
      <Name>Unit GUID</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Reaction</Name>
      <Type>UInt</Type>
      <SegmentType>AIReaction</SegmentType>
    </Simple>
  </RealmPacket>
</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/GameObjects.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">

  <RealmPacket OpCode="CMSG_GAMEOBJ_REPORT_USE">
    <Simple>
      <Name>ObjectId</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>
  
  <RealmPacket OpCode="SMSG_GAMEOBJECT_DESPAWN_ANIM">
    <Simple>
      <Name>ObjectId</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>
</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/Misc.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">

  <RealmPacket OpCode="CMSG_NAME_QUERY">
    <Simple>
      <Name>Entity</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_SET_SELECTION">
    <Simple>
      <Name>Entity</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>
  
  <RealmPacket OpCode="SMSG_EMOTE">
    <Simple>
      <Name>Emote</Name>
      <Type>UInt</Type>
      <SegmentType>Misc.EmoteType</SegmentType>
    </Simple>
    <Simple>
      <Name>Source</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_PLAY_OBJECT_SOUND">
    <Simple>
      <Name>Sound</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Source</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_PLAY_SOUND">
    <Simple>
      <Name>Sound</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_PLAY_MUSIC">
	<Simple>
	  <Name>Sound</Name>
	  <Type>UInt</Type>
	</Simple>
  </RealmPacket>
  
  <RealmPacket OpCode="CMSG_AREATRIGGER">
    <Simple>
      <Name>AreaTrigger</Name>
      <Type>UInt</Type>
      <SegmentType>AreaTriggers.AreaTriggerId</SegmentType>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_ACTION_BUTTONS">
    <Simple>
      <Name>Spec</Name>
      <Type>Byte</Type>
    </Simple>

    <StaticList Length="132">
      <Name>Action Buttons</Name>
      <Simple>
        <Name>Button</Name>
        <Type>Int</Type>
      </Simple>
    </StaticList>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_LOGOUT_COMPLETE"/>

  <RealmPacket OpCode="SMSG_DESTROY_OBJECT">
    <Simple>
      <Name>Object</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Unk Unit Byte</Name>
      <Type>Byte</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_PLAYED_TIME" />
  
  <RealmPacket OpCode="SMSG_PLAYED_TIME">
    <Simple>
      <Name>Total Time Played</Name>
      <Type>Int</Type>
    </Simple>
    <Simple>
      <Name>Time Played This Level</Name>
      <Type>Int</Type>
    </Simple> 
  </RealmPacket>

  <RealmPacket OpCode="SMSG_ACCOUNT_DATA_TIMES">
    <Simple>
      <Name>Server Time</Name>
      <Type>UnixTime</Type>
    </Simple>
    <Simple>
      <Name>UnkByte</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>Mask</Name>
      <Type>UInt</Type>
    </Simple>

    <!--TODO: Add some kind of bit-mask-dependent list type-->
    <!--<StaticList Length="8">
      <Name>Timestamps</Name>
      <Simple>
        <Name>Time</Name>
        <Type>UnixTime</Type>
      </Simple>
    </StaticList>-->

  </RealmPacket>

  <RealmPacket OpCode="CMSG_UPDATE_ACCOUNT_DATA">
    <Simple>
      <Name>Type</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Timestamp</Name>
      <Type>UnixTime</Type>
    </Simple>
    <Simple>
      <Name>Size</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="MSG_SET_DUNGEON_DIFFICULTY">
    <Simple>
      <Name>DifficultyIndex</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Int 2</Name>
      <Type>Int</Type>
    </Simple>
    <Simple>
      <Name>IsInGroup</Name>
      <Type>Int</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_ZONEUPDATE">
    <Simple>
      <Name>New Zone Id</Name>
      <Type>Int</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_INSPECT_TALENT">
    <Simple>
      <Name>FreePoints</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_FORCE_MOVE_UNROOT">
    <Simple>
      <Name>Entity</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <Simple>
      <Name>UnkNum</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_EXPLORATION_EXPERIENCE">
    <Simple>
      <Name>Zone</Name>
      <Type>UInt</Type>
      <SegmentType>World.ZoneId</SegmentType>
    </Simple>
    <Simple>
      <Name>Amount</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_DEATH_RELEASE_LOC" Sender="Server">
    <Simple>
      <Name>SHRegion</Name>
      <Type>UInt</Type>
      <SegmentType>World.MapId</SegmentType>
    </Simple>
    <Simple>
      <Name>SHPos</Name>
      <Type>Vector3</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_REPOP_REQUEST"/>

  <RealmPacket OpCode="SMSG_PRE_RESURRECT">
    <Simple>
      <Name>Entity</Name>
      <Type>PackedGuid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="MSG_CORPSE_QUERY" Sender="Client"/>

  <RealmPacket OpCode="MSG_CORPSE_QUERY" Sender="Server">
    <Simple>
      <Name>Active</Name>
      <Type>Byte</Type>
    </Simple>
    <Switch CompareWith="Active">
      <Case Equals="1">
        <Simple>
          <Name>MapId</Name>
          <Type>UInt</Type>
          <SegmentType>World.MapId</SegmentType>
        </Simple>
        <Simple>
          <Name>Pos</Name>
          <Type>Vector3</Type>
        </Simple>
        <Simple>
          <Name>MapId2</Name>
          <Type>UInt</Type>
          <SegmentType>World.MapId</SegmentType>
        </Simple>
      </Case>
    </Switch>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_CORPSE_RECLAIM_DELAY">
    <Simple>
      <Name>Millis</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_PING">
    <Simple>
      <Name>Sequence</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Latency</Name>
      <Type>Int</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_PONG">
    <Simple>
      <Name>Sequence</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_LFG_SET_ROLES">
    <Simple>
      <Name>Role Mask</Name>
      <Type>Byte</Type>
      <SegmentType>Relations.LFGRolesMask</SegmentType>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_POWER_UPDATE">
    <Simple>
      <Name>Character</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <Simple>
      <Name>Power Type</Name>
      <Type>Byte</Type>
      <SegmentType>PowerType</SegmentType>
    </Simple>
    <Simple>
      <Name>Value</Name>
      <Type>Int</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_LOGIN_SETTIMESPEED">
    <Simple>
      <Name>Date/Time</Name>
      <Type>UnixTime</Type>
    </Simple>
    <Simple>
      <Name>Time Speed</Name>
      <Type>Float</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_LOG_XPGAIN">
    <Simple>
      <Name>Victim</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Total XP Gained</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Xp Type</Name>
      <Type>Byte</Type>
      <SegmentType>WCell.Constants.Xp.XpType</SegmentType>
    </Simple>
    <Switch CompareWith="Xp Type">
      <Case Equals="Kill">
        <Simple>
          <Name>Xp minus Rest Bonus</Name>
          <Type>Int</Type>
        </Simple>
        <Simple>
          <Name>Percent Not Group Bonus</Name>
          <Type>Float</Type>
        </Simple>
      </Case>
    </Switch>
    <Simple>
      <Name>Unknown Byte</Name>
      <Type>Byte</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_TOGGLE_PVP">
    <FinalList>
      <Name>Toggle PvP</Name>
      <Simple>
        <Name>Allow PvP?</Name>
        <Type>Byte</Type>
      </Simple>
    </FinalList>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_BARBER_SHOP_RESULT">
    <Simple>
      <Name>Purchase Result</Name>
      <Type>UInt</Type>
      <SegmentType>NPCs.BarberShopPurchaseResult</SegmentType>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_ENABLE_BARBER_SHOP">
  </RealmPacket>

  <RealmPacket OpCode="CMSG_ALTER_APPEARANCE">
    <Simple>
      <Name>Hair Style</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Hair Color</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Facial Hair Style</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_HEALTH_UPDATE">
    <Simple>
      <Name>Entity</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <Simple>
      <Name>Health</Name>
      <Type>Int</Type>
    </Simple>
  </RealmPacket>
	
	<RealmPacket OpCode="CMSG_GET_MIRRORIMAGE_DATA">
		<Simple>
			<Name>Entity</Name>
			<Type>Guid</Type>
		</Simple>
	</RealmPacket>

</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/Vendors.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">
  <RealmPacket OpCode="CMSG_LIST_INVENTORY">
    <Simple>
      <Name>Vendor EntityId</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_SELL_ITEM">
    <Simple>
      <Name>Vendor EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Item EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Number to Sell</Name>
      <Type>Byte</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_BUYBACK_ITEM">
    <Simple>
      <Name>Vendor EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Buyback Slot</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_BUY_ITEM_IN_SLOT">
    <Simple>
      <Name>Vendor EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Item Template Id</Name>
      <Type>UInt</Type>
      <SegmentType>Items.ItemId</SegmentType>
    </Simple>
    <Simple>
      <Name>Bag EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Bag Slot Id</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>Number to Buy</Name>
      <Type>Byte</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_BUY_ITEM">
    <Simple>
      <Name>Vendor EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Item Template Id</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Number to Buy</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>Unk1</Name>
      <Type>Int</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_SELL_ITEM">
    <Simple>
      <Name>Vendor EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Item EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Error Code</Name>
      <Type>Byte</Type>
      <SegmentType>WCell.Constants.Items.SellItemError</SegmentType>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_BUY_FAILED">
    <Simple>
      <Name>Vendor EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Item Template Id</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Error Code</Name>
      <Type>Byte</Type>
      <SegmentType>WCell.Constants.Items.BuyItemError</SegmentType>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_BUY_ITEM">
    <Simple>
      <Name>Vendor EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Item Template Id</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Bought in stacks of size:</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Number of stacks bought:</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_LIST_INVENTORY">
    <Simple>
      <Name>Vendor EntityId</Name>
      <Type>Guid</Type>
    </Simple>
    <List>
      <Name>NumberOfItems</Name>
      <Type>Byte</Type>
      <Simple>
        <Name>ItemNumber</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>TemplateId</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>DisplayId</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>NumberForSale</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>PricePerStack</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>MaxDurability</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>StackSize</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>ExtendedCostId</Name>
        <Type>UInt</Type>
      </Simple>
    </List>
  </RealmPacket>
</Definitions>
