=== onikolaiev/netServer/Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Definitions">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="RealmPacket" type="packetDefinition"/>
        <xs:element name="AuthPacket" type="packetDefinition"/>
      </xs:choice>
      <xs:attribute name="Version" type="xs:positiveInteger"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="packetDefinition">
        <xs:sequence>
          <xs:element name="OpCodes" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="OpCode" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
        </xs:element>
        <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="OpCode" type="xs:string" use="optional"/>
        <xs:attribute name="Sender" use="optional">
          <xs:simpleType id="PacketSender">
            <xs:restriction base="xs:string">
              <xs:enumeration value="Client"/>
              <xs:enumeration value="Server"/>
              <xs:enumeration value="Any"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
</xs:complexType>

      <xs:group name="optionallyNamedSegmentList">
        <xs:sequence>
          <xs:element name="Name" type="xs:string" minOccurs="0"/>
          <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:group>

      <xs:group name="segmentList">
        <xs:choice>
          <xs:element name="Simple">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Type" type="simpleType"/>
                <xs:element name="SegmentType" type="xs:string" minOccurs="0" maxOccurs="1"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="Complex">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string" minOccurs="0"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="List">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Type" type="simpleType" minOccurs="0"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
              <xs:attribute name="LengthSegment" type="xs:string" use="optional"/>
              <xs:attribute name="LengthExpr" type="xs:string" use="optional"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="StaticList">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
              <xs:attribute name="Length" type="xs:positiveInteger"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="Switch">
            <xs:complexType>
              <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="Case">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                    <xs:attribute name="Equals" use="optional"/>
                    <xs:attribute name="NotEqual" use="optional"/>
                    <xs:attribute name="GreaterThan" use="optional"/>
                    <xs:attribute name="GreaterOrEqual" use="optional"/>
                    <xs:attribute name="LessThan" use="optional"/>
                    <xs:attribute name="LessOrEqual" use="optional"/>
                    <xs:attribute name="And" use="optional"/>
                    <xs:attribute name="AndAny" use="optional"/>
                    <xs:attribute name="AndNot" use="optional"/>
                    <xs:attribute name="Either" use="optional"/>
                    <xs:attribute name="Neither" use="optional"/>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
              <xs:attribute name="CompareWith" type="xs:string"/>
            </xs:complexType>
          </xs:element>
          <xs:element name="FinalList">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Name" type="xs:string"/>
                <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:choice>
      </xs:group>

      <xs:group name="namedSegmentList">
        <xs:sequence>
          <xs:element name="Name" type="xs:string"/>
          <xs:group ref="segmentList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:group>

      <xs:simpleType name="simpleType">
        <xs:restriction base="xs:string">
          <xs:enumeration value="Byte"/>
          <xs:enumeration value="UShort"/>
          <xs:enumeration value="Short"/>
          <xs:enumeration value="UInt"/>
          <xs:enumeration value="Int"/>
          <xs:enumeration value="ULong"/>
          <xs:enumeration value="Long"/>
          <xs:enumeration value="Float"/>
          <xs:enumeration value="Guid"/>
          <xs:enumeration value="Vector3"/>
          <xs:enumeration value="PackedVector3"/>
          <xs:enumeration value="Vector4"/>
          <xs:enumeration value="PackedGuid"/>
          <xs:enumeration value="CString"/>
          <xs:enumeration value="PascalStringByte"/>
          <xs:enumeration value="PascalStringUShort"/>
          <xs:enumeration value="PascalStringUInt"/>
          <xs:enumeration value="Guid"/>
		  <xs:enumeration value="UnixTime"/>
		  <xs:enumeration value="PackedDate"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:schema>

=== onikolaiev/netServer/Run/Content/Packets/Talents.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">

  <RealmPacket OpCode="CMSG_LEARN_TALENT" Sender="Client">
    <Simple>
      <Name>Talent Id</Name>
      <Type>Int</Type>
      <SegmentType>Talents.TalentId</SegmentType>
    </Simple>
    <Simple>
      <Name>Rank</Name>
      <Type>Int</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_PET_LEARN_TALENT" Sender="Client">
    <Simple>
      <Name>Pet</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Talent Id</Name>
      <Type>Int</Type>
      <SegmentType>Talents.TalentId</SegmentType>
    </Simple>
    <Simple>
      <Name>Rank</Name>
      <Type>Int</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="MSG_TALENT_WIPE_CONFIRM" Sender="Server">
    <Simple>
      <Name>Trainer</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Reset Cost</Name>
      <Type>Int</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="MSG_TALENT_WIPE_CONFIRM" Sender="Client">
    <Simple>
      <Name>Trainer</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_TALENTS_INFO" Sender="Server">
    <Simple>
      <Name>IsPet</Name>
      <Type>Byte</Type>
    </Simple>
    <Switch CompareWith="IsPet">
      <Case Equals="0">
        <!-- Player -->
        <Simple>
          <Name>Unspent Talent Points</Name>
          <Type>Int</Type>
        </Simple>
        <Simple>
          <Name>Talent Group Count</Name>
          <Type>Byte</Type>
        </Simple>
        <Simple>
          <Name>Talent Group Index</Name>
          <Type>Byte</Type>
        </Simple>

        <List LengthSegment="Talent Group Count">
          <Name>Talent Groups</Name>

          <List>
            <Name>Talents</Name>
            <Type>Byte</Type>

            <Simple>
              <Name>Talent Id</Name>
              <Type>Int</Type>
              <SegmentType>Talents.TalentId</SegmentType>
            </Simple>
            <Simple>
              <Name>Rank</Name>
              <Type>Byte</Type>
            </Simple>
          </List>

          <List>
            <Name>Glyphs</Name>
            <Type>Byte</Type>

            <Simple>
              <Name>Glyph</Name>
              <Type>Short</Type>
            </Simple>
          </List>

        </List>
      </Case>
      <Case Equals="1">
        <!-- Pet -->
        <Simple>
          <Name>FreeTalentPoints</Name>
          <Type>Int</Type>
        </Simple>

        <List>
          <Name>Talents</Name>
          <Type>Byte</Type>

          <Simple>
            <Name>TalentId</Name>
            <Type>Int</Type>
            <SegmentType>Talents.TalentId</SegmentType>
          </Simple>
          <Simple>
            <Name>Rank</Name>
            <Type>Byte</Type>
          </Simple>
        </List>
      </Case>
    </Switch>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_LEARN_PREVIEWED_TALENTS" Sender="Client">
    <List>
      <Name>Talents</Name>
      <Type>Int</Type>

      <Simple>
        <Name>Talent Id</Name>
        <Type>Int</Type>
        <SegmentType>Talents.TalentId</SegmentType>
      </Simple>
      <Simple>
        <Name>Rank</Name>
        <Type>Int</Type>
      </Simple>
    </List>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_PET_LEARN_PREVIEWED_TALENTS" Sender="Client">
    <Simple>
      <Name>Pet</Name>
      <Type>Guid</Type>
    </Simple>
    <List>
      <Name>Talents</Name>
      <Type>Int</Type>

      <Simple>
        <Name>Talent Id</Name>
        <Type>Int</Type>
        <SegmentType>Talents.TalentId</SegmentType>
      </Simple>
      <Simple>
        <Name>Rank</Name>
        <Type>Int</Type>
      </Simple>
    </List>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_SET_PROFICIENCY">
    <Simple>
      <Name>Item Class</Name>
      <Type>Byte</Type>
      <SegmentType>Items.ItemClass</SegmentType>
    </Simple>
    <Simple>
      <Name>Item SubClass Mask</Name>
      <Type>UInt</Type>
      <SegmentType>Items.ItemSubClassMask</SegmentType>
    </Simple>
  </RealmPacket>
</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/VoiceChat.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">

  <RealmPacket OpCode="CMSG_SET_ACTIVE_VOICE_CHANNEL">
    <Simple>
      <Name>Channel Id (?)</Name>
      <Type>Int</Type>
    </Simple>
    <Simple>
      <Name>Unknown Byte</Name>
      <Type>Byte</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_VOICE_SESSION_ENABLE">
    <Simple>
      <Name>Voice Enabled (bool)</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>Mic Enabled (bool)</Name>
      <Type>Byte</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_FEATURE_SYSTEM_STATUS">
    <Simple>
      <Name>Unknown Const: 2</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>System Status</Name>
      <Type>Byte</Type>
      <SegmentType>VoiceSystemStatus</SegmentType>
    </Simple>
  </RealmPacket>
</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/Achievements.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">

    <RealmPacket OpCode="SMSG_SERVER_FIRST_ACHIEVEMENT">
      <Simple>
        <Name>Player name</Name>
        <Type>CString</Type>
      </Simple>
      <Simple>
        <Name>Player GUID</Name>
        <Type>Guid</Type>
      </Simple>
      <Simple>
        <Name>Achievement ID</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>Link in chat (1 = yes)</Name>
        <Type>UInt</Type>
      </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_ACHIEVEMENT_EARNED">
    <Simple>
      <Name>Player GUID</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <Simple>
      <Name>Achievement ID</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Time</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Unknown</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_CRITERIA_UPDATE">
    <Simple>
      <Name>Criteria ID</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Progress counter</Name>
      <!-- the counter is packed like a packed Guid -->
      <Type>PackedGuid</Type>
    </Simple>
    <Simple>
      <Name>Player GUID</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <Simple>
      <Name>Unknown 1</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Time</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Unknown Timer 1</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>Unknown Timer 2</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>
  <RealmPacket OpCode="SMSG_ACHIEVEMENT_DELETED">
    <Simple>
      <Name>Achievement ID</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_CRITERIA_DELETED">
    <Simple>
      <Name>Criteria ID</Name>
      <Type>UInt</Type>
    </Simple>
  </RealmPacket>

<!--
  <RealmPacket OpCode="SMSG_ALL_ACHIEVEMENT_DATA">
    <FinalList>
      <Simple>
        <Name>Achievement ID</Name>
        <Type>Int</Type>
      </Simple>
      <Simple>
        <Name>Time achieved</Name>
        <Type>UInt</Type>
      </Simple>
      <Switch CompareWith="Achievement ID"></Switch>
        <Case Equal="-1">
          <FinalList>
            <Simple>
              <Name>Criteria ID</Name>
              <Type>UInt</Type>
            </Simple>
            <Simple>
              <Name>Progress counter</Name>
              <Type>PackedGuid</Type>
            </Simple>
            <Simple>
              <Name>Player GUID</Name>
              <Type>PackedGuid</Type>
            </Simple>
            <Simple>
              <Name>Unknown 1</Name>
              <Type>UInt</Type>
            </Simple>
            <Simple>
              <Name>Time</Name>
              <Type>UInt</Type>
            </Simple>
            <Simple>
              <Name>Unknown Timer 1</Name>
              <Type>UInt</Type>
            </Simple>
            <Simple>
              <Name>Unknown Timer 2</Name>
              <Type>UInt</Type>
            </Simple>
          </FinalList>
      </Case>
    </FinalList>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_RESPOND_INSPECT_ACHIEVEMENTS">
    <Simple>
      <Name>Player GUID</Name>
      <Type>PackedGuid</Type>
    </Simple>
    <FinalList>
      <Simple>
        <Name>Achievement ID</Name>
        <Type>Int</Type>
      </Simple>
      <Simple>
        <Name>Time achieved</Name>
        <Type>UInt</Type>
      </Simple>
      <Switch CompareWith="Achievement ID"></Switch>
      <Case Equal="-1">
        <FinalList>
          <Simple>
            <Name>Criteria ID</Name>
            <Type>UInt</Type>
          </Simple>
          <Simple>
            <Name>Progress counter</Name>
            <Type>PackedGuid</Type>
          </Simple>
          <Simple>
            <Name>Player GUID</Name>
            <Type>PackedGuid</Type>
          </Simple>
          <Simple>
            <Name>Unknown 1</Name>
            <Type>UInt</Type>
          </Simple>
          <Simple>
            <Name>Time</Name>
            <Type>UInt</Type>
          </Simple>
          <Simple>
            <Name>Unknown Timer 1</Name>
            <Type>UInt</Type>
          </Simple>
          <Simple>
            <Name>Unknown Timer 2</Name>
            <Type>UInt</Type>
          </Simple>
        </FinalList>
      </Case>
    </FinalList>
  </RealmPacket>  
-->
  
</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/Trainers.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">
  <RealmPacket OpCode="SMSG_TRAINER_LIST">
    <Simple>
      <Name>Trainer</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Trainer Type</Name>
      <Type>Int</Type>
    </Simple>
    <List>
      <Name>Spells</Name>
      <Type>Int</Type>

      <Simple>
        <Name>Spell</Name>
        <Type>UInt</Type>
        <SegmentType>Spells.SpellId</SegmentType>
      </Simple>
      <Simple>
        <Name>LearnState</Name>
        <Type>Byte</Type>
<!--        <SegmentType>NPCs.TrainerSpellState</SegmentType> -->
      </Simple>
      <Simple>
        <Name>MoneyCost</Name>
        <Type>Int</Type>
      </Simple>
      <Simple>
        <Name>TalentCost</Name>
        <Type>Int</Type>
      </Simple>
      <Simple>
        <Name>ProfessionPointCost</Name>
        <Type>Int</Type>
      </Simple>
      <Simple>
        <Name>RequiredLevel</Name>
        <Type>Byte</Type>
      </Simple>

      <Simple>
        <Name>RequiredSkill</Name>
        <Type>UInt</Type>
        <SegmentType>Skills.SkillId</SegmentType>
      </Simple>
      <Simple>
        <Name>RequiredSkillLevel</Name>
        <Type>Int</Type>
      </Simple>

      <Simple>
        <Name>RequiredSpellId1</Name>
        <Type>UInt</Type>
        <SegmentType>Spells.SpellId</SegmentType>
      </Simple>
      <Simple>
        <Name>RequiredSpellId2</Name>
        <Type>UInt</Type>
        <SegmentType>Spells.SpellId</SegmentType>
      </Simple>
      <Simple>
        <Name>RequiredSpellId3</Name>
        <Type>UInt</Type>
        <SegmentType>Spells.SpellId</SegmentType>
      </Simple>
    </List>
    <Simple>
      <Name>GreetingText</Name>
      <Type>CString</Type>
    </Simple>
  </RealmPacket>
</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/Relations.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">

  <RealmPacket OpCode="CMSG_ADD_FRIEND">
    <Simple>
      <Name>Name</Name>
      <Type>CString</Type>
    </Simple>
    <Simple>
      <Name>Note</Name>
      <Type>CString</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_DEL_FRIEND">
    <Simple>
      <Name>CharacterId</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_SET_CONTACT_NOTES">
    <Simple>
      <Name>CharacterId</Name>
      <Type>Guid</Type>
    </Simple>
    <Simple>
      <Name>Note</Name>
      <Type>CString</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_ADD_IGNORE">
    <Simple>
      <Name>Name</Name>
      <Type>CString</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_DEL_IGNORE">
    <Simple>
      <Name>CharacterId</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <!-- Unknown packet defs
  <RealmPacket OpCode="CMSG_ADD_MUTED">
    <Simple>
      <Name>Name</Name>
      <Type>CString</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_DEL_MUTED">
    <Simple>
      <Name>CharacterId</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>
  -->

  <RealmPacket OpCode="SMSG_FRIEND_STATUS">
    <Simple>
      <Name>ResultCode</Name>
      <Type>Byte</Type>
      <SegmentType>RelationResult</SegmentType>
    </Simple>
    <Simple>
      <Name>Id</Name>
      <Type>Guid</Type>
    </Simple>
    <Switch CompareWith="ResultCode">
      <Case Equals="FRIEND_OFFLINE">
        <Simple>
          <Name>Status</Name>
          <Type>Byte</Type>
          <SegmentType>CharacterStatus</SegmentType>
        </Simple>
      </Case>
      <Case Equals="FRIEND_ADDED_OFFLINE">
        <Simple>
          <Name>Note</Name>
          <Type>CString</Type>
        </Simple>
      </Case>
      <Case Equals="FRIEND_ADDED_ONLINE">
        <Simple>
          <Name>Note</Name>
          <Type>CString</Type>
        </Simple>
        <Simple>
          <Name>Status</Name>
          <Type>Byte</Type>
          <SegmentType>CharacterStatus</SegmentType>
        </Simple>
        <Simple>
          <Name>Zone</Name>
          <Type>UInt</Type>
          <SegmentType>World.ZoneId</SegmentType>
        </Simple>
        <Simple>
          <Name>Level</Name>
          <Type>UInt</Type>
        </Simple>
        <Simple>
          <Name>Class</Name>
          <Type>UInt</Type>
          <SegmentType>ClassId</SegmentType>
        </Simple>
      </Case>
      <Case Equals="FRIEND_ONLINE">
        <Simple>
          <Name>Status</Name>
          <Type>Byte</Type>
          <SegmentType>CharacterStatus</SegmentType>
        </Simple>
        <Simple>
          <Name>Zone</Name>
          <Type>UInt</Type>
          <SegmentType>World.ZoneId</SegmentType>
        </Simple>
        <Simple>
          <Name>Level</Name>
          <Type>UInt</Type>
        </Simple>
        <Simple>
          <Name>Class</Name>
          <Type>UInt</Type>
          <SegmentType>ClassId</SegmentType>
        </Simple>
      </Case>
    </Switch>
  </RealmPacket>

  <RealmPacket OpCode="CMSG_CONTACT_LIST">
    <Simple>
      <Name>RequestedList</Name>
      <Type>UInt</Type>
      <SegmentType>Relations.RelationTypeFlag</SegmentType>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_CONTACT_LIST">
    <Simple>
      <Name>RequestedList</Name>
      <Type>UInt</Type>
      <SegmentType>Relations.RelationTypeFlag</SegmentType>
    </Simple>
    <List>
      <Name>Contacts</Name>
      <Type>UInt</Type>
      <Simple>
        <Name>ContactId</Name>
        <Type>Guid</Type>
      </Simple>
      <Simple>
        <Name>ContactFlags</Name>
        <Type>UInt</Type>
        <SegmentType>Relations.RelationTypeFlag</SegmentType>
      </Simple>
      <Simple>
        <Name>ContactNote</Name>
        <Type>CString</Type>
      </Simple>
      <Switch CompareWith="ContactFlags">
        <Case And="Friend">
          <Simple>
            <Name>ContactStatus</Name>
            <Type>Byte</Type>
            <SegmentType>CharacterStatus</SegmentType>
          </Simple>
          <Switch CompareWith="ContactStatus">
            <Case NotEqual="OFFLINE">
              <Simple>
                <Name>ContactZone</Name>
                <Type>UInt</Type>
                <SegmentType>World.ZoneId</SegmentType>
              </Simple>
              <Simple>
                <Name>ContactLevel</Name>
                <Type>UInt</Type>
              </Simple>
              <Simple>
                <Name>ContactClass</Name>
                <Type>UInt</Type>
                <SegmentType>ClassId</SegmentType>
              </Simple>
            </Case>
          </Switch>
        </Case>
      </Switch>
    </List>
  </RealmPacket>
  
</Definitions>

=== onikolaiev/netServer/Run/Content/Packets/Login.xml
<?xml version="1.0" encoding="utf-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xsi:schemaLocation=". ../../../../Utilities/WCell.PacketAnalyzer/Xml/PacketAnalyzerSchema.xsd"
             Version="4">
  
  <RealmPacket Sender="Client" OpCode="CMSG_REALM_SPLIT">
    <Simple>
      <Name>Unknown1</Name>
      <Type>UShort</Type>
    </Simple>
    <Simple>
      <Name>Unknown2</Name>
      <Type>UShort</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_REALM_SPLIT">
    <Simple>
      <Name>Unknown1</Name>
      <Type>UInt</Type>
    </Simple>
    <Simple>
      <Name>RealmState</Name>
      <Type>UInt</Type>
      <SegmentType>Login.RealmState</SegmentType>
    </Simple>
    <Simple>
      <Name>SplitDate</Name>
      <Type>CString</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket Sender="Client" OpCode="CMSG_CHAR_ENUM">
    <!--Only happens sometimes:
    <Simple>
      <Name>Unknown1</Name>
      <Type>UShort</Type>
    </Simple>-->
  </RealmPacket>

  <RealmPacket OpCode="SMSG_CHAR_ENUM">
    <List>
      <Name>Characters</Name>
      <Type>Byte</Type>
      <Simple>
        <Name>Id</Name>
        <Type>Guid</Type>
      </Simple>
      <Simple>
        <Name>Name</Name>
        <Type>CString</Type>
      </Simple>
      <Simple>
        <Name>Race</Name>
        <Type>Byte</Type>
        <SegmentType>RaceId</SegmentType>
      </Simple>
      <Simple>
        <Name>Class</Name>
        <Type>Byte</Type>
        <SegmentType>ClassId</SegmentType>
      </Simple>
      <Simple>
        <Name>Gender</Name>
        <Type>Byte</Type>
        <SegmentType>GenderType</SegmentType>
      </Simple>
      <Simple>
        <Name>Skin</Name>
        <Type>Byte</Type>
      </Simple>
      <Simple>
        <Name>Face</Name>
        <Type>Byte</Type>
      </Simple>
      <Simple>
        <Name>HairStyle</Name>
        <Type>Byte</Type>
      </Simple>
      <Simple>
        <Name>HairColor</Name>
        <Type>Byte</Type>
      </Simple>
      <Simple>
        <Name>FacialHair</Name>
        <Type>Byte</Type>
      </Simple>
      <Simple>
        <Name>Level</Name>
        <Type>Byte</Type>
      </Simple>
      <Simple>
        <Name>Zone</Name>
        <Type>UInt</Type>
        <SegmentType>WCell.Constants.World.ZoneId</SegmentType>
      </Simple>
      <Simple>
        <Name>Region</Name>
        <Type>UInt</Type>
        <SegmentType>WCell.Constants.World.MapId</SegmentType>
      </Simple>
      <Simple>
        <Name>X</Name>
        <Type>Float</Type>
      </Simple>
      <Simple>
        <Name>Y</Name>
        <Type>Float</Type>
      </Simple>
      <Simple>
        <Name>Z</Name>
        <Type>Float</Type>
      </Simple>
      <Simple>
        <Name>Guild</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>CharacterFlags</Name>
        <Type>UInt</Type>
        <SegmentType>Login.CharEnumFlags</SegmentType>
      </Simple>
      <Simple>
        <Name>CustomizationFlags</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>FirstLogin</Name>
        <Type>Byte</Type>
      </Simple>
      <Simple>
        <Name>PetDisplayId</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>PetLevel</Name>
        <Type>UInt</Type>
      </Simple>
      <Simple>
        <Name>PetFamily</Name>
        <Type>UInt</Type>
        <SegmentType>NPCs.CreatureFamilyId</SegmentType>
      </Simple>

      <StaticList Length="23">
        <Name>Items</Name>
        <Simple>
          <Name>DisplayId</Name>
          <Type>UInt</Type>
        </Simple>
        <Simple>
          <Name>InventorySlotType</Name>
          <Type>Byte</Type>
          <SegmentType>Items.InventorySlotType</SegmentType>
        </Simple>
        <Simple>
          <Name>EnchantSpellId</Name>
          <Type>UInt</Type>
          <Type>WCell.Constants.Spells.SpellId</Type>
        </Simple>
      </StaticList>
    </List>
  </RealmPacket>

  <RealmPacket Sender="Client" OpCode="CMSG_CHAR_CREATE">
    <Simple>
      <Name>Name</Name>
      <Type>CString</Type>
    </Simple>
    <Simple>
      <Name>Race</Name>
      <Type>Byte</Type>
      <SegmentType>RaceId</SegmentType>
    </Simple>
    <Simple>
      <Name>Class</Name>
      <Type>Byte</Type>
      <SegmentType>ClassId</SegmentType>
    </Simple>
    <Simple>
      <Name>Gender</Name>
      <Type>Byte</Type>
      <SegmentType>GenderType</SegmentType>
    </Simple>
    <Simple>
      <Name>Skin</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>Face</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>HairStyle</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>HairColor</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>FacialHair</Name>
      <Type>Byte</Type>
    </Simple>
    <Simple>
      <Name>Outfit</Name>
      <Type>Byte</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket Sender="Client" OpCode="CMSG_VOICE_SESSION_ENABLE">
    <Simple>
      <Name>Enabled</Name>
      <Type>UShort</Type>
    </Simple>
  </RealmPacket>
  
  <RealmPacket OpCode="SMSG_MOTD">
    <List>
      <Name>Messages</Name>
      <Type>UInt</Type>
      <Simple>
        <Name>Message</Name>
        <Type>CString</Type>
      </Simple>
    </List>
  </RealmPacket>

  <RealmPacket Sender="Client" OpCode="CMSG_PLAYER_LOGIN">
    <Simple>
      <Name>CharacterId</Name>
      <Type>Guid</Type>
    </Simple>
  </RealmPacket>

  <RealmPacket OpCode="SMSG_LOGIN_VERIFY_WORLD">
    <Simple>
      <Name>Region Id</Name>
      <Type>Int</Type>
      <SegmentType>World.MapId</SegmentType>
    </Simple>
    <Simple>
      <Name>Position</Name>
      <Type>Vector3</Type>
    </Simple>
    <Simple>
      <Name>Orientation</Name>
      <Type>Float</Type>
    </Simple>
  </RealmPacket>
</Definitions>
